#missiles
- type: entity
  id: MissileBase
  parent: BaseStructure
  name: supply drop pod
  description: A standard-issue Nanotrasen storage unit.
  abstract: true
  components:
  - type: Physics
    bodyType: Static
  - type: Sprite
    noRot: true
  - type: MovedByPressure
  - type: ItemSlots
  - type: DamageOnHighSpeedImpact
    damage:
      types:
        Blunt: 5
    soundHit:
      collection: MetalThud
  - type: InteractionOutline
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.25,-0.48,0.25,0.48"
        density: 75
        mask:
        - MachineMask
        layer:
        - MachineLayer
  - type: PlaceableSurface
    placeCentered: true
    isPlaceable: false
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: StructuralMetallic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 300
      behaviors:
        - !type:DoActsBehavior
          acts: [ "Destruction" ]
    - trigger:
        !type:DamageTrigger
        damage: 150
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
      - !type:PlaySoundBehavior
        sound:
          collection: MetalBreak
          params:
            volume: -6
      - !type:SpawnEntitiesBehavior
        spawn:
          SheetSteel1:
            min: 1
            max: 1
  - type: Appearance
  - type: EmitSoundOnSpawn
    sound:
      collection:
        BIGEXPLOSION
      params:
        volume: 5
  - type: StaticPrice
    price: 75
  - type: ConditionalSpawner
    prototypes:
    - GibZone

- type: entity
  id: GibZone
  name: gibbing zone
  description: A zone when you step her, you got gibbed. If you see that, you are probably dead.
  components:
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        hard: false
        density: 7
        shape:
          !type:PhysShapeAabb
           bounds: "-0.5,-0.5,0.5,0.5"
        layer:
        - MidImpassable
  - type: Transform
    anchored: true
  - type: DamageContacts
    damage:
      types:
        Blunt: 1000
  - type: TimedDespawn
    lifetime: 1
